apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
    - name: mongo
      image: mongo:6.0
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
      volumes:
        - name: mongo-volume
          emptyDir: {} ## This is pod level
          hostPath:
            path: /data ## This on a host level
